### ISSUE TITLE
cartesian and output folders to restructure for tracking progresses

### ISSUE THREAD

**Issue by elenapapaleo** [ELELAB/RosettaDDGPrediction#27]
One big challenge with the saturation scans and the cartesian mode is that all the output folders are created before starting the scans and it is hard for the user to immediately understand how many mutations are missing or how many have been done when you check on the progresses. This becomes especially problematic when using HPC resources in planning wall-clock and resources for resubmission. I would prefer to see that we create the folders progressively if possible and also if we can allocate the processes in order of the numbering of the sequence so that the residues in N-terminal enter into the scans first.

**Comment by ValeSora** [comment]
I think this error has been solved as a by-product of the recent code restructuring that has been done to solve the core-occupancy issues (i.e., cores not being fully used despite being allocated). Therefore, now each mutation folder is created only immediately before launching the corresponding process, and they are not created all together at the beginning of the run.

**Comment by elenapapaleo** [comment]
yes i can confirm this and we can close this issue :)
