### ISSUE TITLE
rosetta_ddg_check_run improvements for crashes due to wrong versions

### ISSUE THREAD

**Issue by elenapapaleo** [ELELAB/RosettaDDGPrediction#48]
if the run crashes without even writing in the folders or without a LOG of the crash in the mutation folders, rosetta_ddg_check_run will exit without problems so we should handle it better for transparency to the user

**Comment by ValeSora** [comment]
If no error files are written, `rosetta_ddg_check_run` cannot discriminate between a run that has not happened yet and one that has crashed "quietly".

However, we could implement a WARNING that is raised every time the `rosetta_ddg_run` tool is run in a folder where no files at all have been created (i.e., the mutations sub-folders are empty, or there are no sub-folders at all).

The appearance of such a WARNING would indicate that `rosetta_ddg_run` has never been run or that the run crashed without producing anything, but at that point, it should be fairly easy for the user to discriminate between the two cases.

**Comment by elenapapaleo** [comment]
not sure this will solve what I meant but we can discuss it at the next developer meeting
