### ISSUE TITLE
Dask Stream is Closed

### ISSUE THREAD

**Issue by JaccoVE** [ELELAB/RosettaDDGPrediction#58]
Hi! I'm trying out the pipeline, but I'm having problems with Dask related to this issue:

[https://github.com/dask/distributed/issues/3129](https://github.com/dask/distributed/issues/3129)

I was wondering which Dask and Dask Distributed versions you used to ensure that this problem does not occur.

Thanks!

**Comment by ValeSora** [comment]
Hi!

We have not encountered this problem before. We are currently using the following versions for our calculations:

- `dask` version '2020.12.0'
- `distributed` version '2020.12.0'

Let us know if anything changes by using them!

**Comment by JaccoVE** [comment]
Thanks for sharing! After looking into it a little bit more it seems that all the results are correctly generated even though there is this error message. I think the Dask worker tasks are not exiting correctly somehow. Not sure whether this is specific to my setup or due to something in the code itself.

Anyway, since I could still create the results I was looking for, finding the exact reason for the errors is no longer strictly necessary.
