### ISSUE TITLE
Issues running on MacOS

### ISSUE THREAD

**Issue by livmac101** [ELELAB/RosettaDDGPrediction#67]
I am trying to run on the newest academic version of Rosetta3.14 from GitHub and python 3.12 on MacOS. I believe that I have successfully complied Rosetta properly (although I do not have a main/source/bin within rosetta, but rather just a source/bin). However, I can see all the .macosclangrelease files. I am working on 6SOY and trying to make two different mutations on chains A and B and use the flexddg workflow. When I start a run, it seems to get stuck and no output .pdb files are generated. I suspect it is an issue with the .yaml files, but I am not sure. I used nompi.yaml and edited the location to source/bin and the executables extension to .macosclangrelease. Thank you.

**Comment by livmac101** [comment]
Just to update, I have now downloaded Rosetta 3.12 (rosetta_bin_mac_2020.08.61146_bundle) from the rosetta commons website (which I believe is already compiled). I am also using Python 3.12. I have also tried other version of Python >3.7 without success so far. Using Rosetta 3.14 and Python 3.12, I was able to get .yaml files to run but it got stuck and no output .pdb files were used (as above). Now, using Rosetta 3.12 and Python 3.12, I am getting the following error:

2024-04-09 22:19:06,671 - distributed.worker - WARNING - Compute Failed
Key:       run_flexddg-3b55a96ede0eed0c08776dcddcc4525c
Function:  run_flexddg
args:      ()
kwargs:    {'step_features': {'role': 'ddg', 'run_by': 'rosetta', 'executable': 'rosetta_scripts', 'executable_extract': 'score_jd2'}, 'exec_path': '/Users/oliviamacleod/Desktop/rosetta_bin_mac_2020.08.61146_bundle/main/source/bin', 'exec_suffix': '.macosclangrelease', 'mut': {'_mut_': [{'_chain_': 'A', '_wtr_': 'R', '_numr_': '109', '_mutr_': 'A'}], '_chaintomove_': 'A', '_struct_': '9', '_dirpath_': 'A-R109A/9', '_dirname_': 'A-R109A'}, 'mut_wd': '/Users/oliviamacleod/Desktop/6SOY/flexddg/A-R109A/9', 'step': {'wd': 'flexddg', 'cleanlevel': None, 'flagsfile': 'flags.txt', 'output': 'flexddg.out', 'options': {'-in:ignore_unrecognized_res': 'true', '-in:file:fullatom': 'true', '-out:level': '300', '-out:chname': 'true', '-out:chtimestamp': 'true', '-out:save_times': 'true', '-run:checkpoint': 'true', '-run:version': 'true', '-run:ignore_zero_occupancy': 'false', '-packing:extrachi_cutoff': '18', '-packing:ex1': 'true', '-packing:ex2': 'true', '-parser:protocol': 'Flex_ddG.xml', '-parser:script_var
Exception: "ValueError('No executable found for rosetta_scripts.macosclangrelease in /Users/oliviamacleod/Desktop/rosetta_bin_mac_2020.08.61146_bundle/main/source/bin.')"

**Comment by mtiberti** [comment]
hi @livmac101 , 

thanks for your interest. I see this error in your output:

```
Exception: "ValueError('No executable found for rosetta_scripts.macosclangrelease in /Users/oliviamacleod/Desktop/rosetta_bin_mac_2020.08.61146_bundle/main/source/bin.')"
```

does this file (`/Users/oliviamacleod/Desktop/rosetta_bin_mac_2020.08.61146_bundle/main/source/bin/rosetta_scripts.macosclangrelease`) exist?

Can you paste here your command line and the content of your `nompi.yaml`?

Thanks

**Comment by livmac101** [comment]
Hi @mtiberti, thank you very much for getting back to me! Sorry my questions are a bit unclear. I have been trying a number of different combinations to run your tool on my MacOS, and I am very likely making a lot of mistakes. I have tried Rosetta 3.14, Rosetta 3.12, and Rosetta 2022.11 (the latter two to match those in your manual). I have also tried Python 3.12, 3.7 and 3.6 in case that might be the issue. 

**Re: Rosetta 3.12**
Indeed, I couldn't find the rosetta_scripts.macosclangrelease in the rosetta_bin_mac_2020.08.61146_bundle. I downloaded it directly from the rosetta commons website ([Rosetta 3.12 source + binaries for Mac](https://www.rosettacommons.org/download.php?token=a64t4Q78m&file=rosetta_bin_mac_3.12_bundle.tgz) - as one bundle (14G)), and there were already a number of items in the main/source/bin so I believe it was already compiled. I also tried getting the Rosetta3.12 release from GitHub directly, but had issues compiling this on my MacOS. 

**Re: Rosetta 3.14** 
Do you think I should go back to Rosetta 3.14 and Python 3.12? For this combination I had the most success and I was able to compile and get the .yaml files to run, but the output got 'stuck' immediately and there were no .pdb files generated. I have attached all the files I am trying to use for the run, along with what the run looks like (and gets stuck on). 

Thank you in advance for your help! 

**Input into terminal**
(rosetta_env) oliviamacleod@Olivias-MacBook-Air 6SOY % rosetta_ddg_run -n 4 -p 6SOY_edit.pdb -cr /Users/oliviamacleod/Desktop/6SOY/flexddg_ref2015.yaml -cs /Users/oliviamacleod/Desktop/6SOY/nompi.yaml -r /Users/oliviamacleod/Desktop/rosetta -l listfile.txt --saturation --reslistfile resfile.txt
INFO:root:Now checking the configuration file /Users/oliviamacleod/Desktop/6SOY/nompi.yaml.
INFO:root:Now checking the configuration file /Users/oliviamacleod/Desktop/6SOY/flexddg_ref2015.yaml.
/Users/oliviamacleod/Desktop/rosetta_env/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 9880
  warnings.warn(
2024-04-10 12:08:09,541 - distributed.worker - WARNING - The following mutinfo files have been found in /Users/oliviamacleod/Desktop/6SOY/flexddg: mutinfo.txt. A new file named mutinfo1.txt will be written for this run.
INFO:root:The following mutations will be performed:
A-R109A, A-R109F, A-R109L, A-R109R, B-A223A, B-A223F, B-A223L, B-A223R, A-R109A_B-A223A, A-R109A_B-A223F, A-R109A_B-A223L, A-R109A_B-A223R, A-R109F_B-A223A, A-R109F_B-A223F, A-R109F_B-A223L, A-R109F_B-A223R, A-R109L_B-A223A, A-R109L_B-A223F, A-R109L_B-A223L, A-R109L_B-A223R, A-R109R_B-A223A, A-R109R_B-A223F, A-R109R_B-A223L, A-R109R_B-A223R.

**nompi.yaml**
# Default settings used in rosetta_ddg_run to set up parallel runs, 
# set the logging level and how to find the Rosetta executables.


################################# RUN #################################

mpi:
  # whether to use MPI
  usempi: False
  # MPI executable
  mpiexec: !!null
  # MPI arguments
  mpiargs: !!null

localcluster:
  # level of log silencing (log messages of lower levels will
  # be suppressed)
  silence_logs: "WARNING"
  # whether to use processes, single-core or threads
  processes: True
  # how many threads for each worker
  threads_per_worker: 1


############################### ROSETTA ###############################

rosetta:
  # usual Rosetta path for executables
  execpath: "/Users/oliviamacleod/Desktop/rosetta/source/bin"
  # suffix of the Rosetta executables
  execsuffix: .macosclangrelease

**flexddg_ref2015.yaml** (I changed the number of structures)
# Configuration file needed to run the `flexddg` protocol with
# the `ref2015` scoring function.
#
# The protocol was originally developed by Kortemme Lab [barlow2018]_
# and a slightly modified version of the original XML file containing
# the core of the protocol is available in the RosettaDDGProtocols
# package under `rosetta_scripts/Flex_ddG.xml`.
#
# .. [barlow2018] Barlow, Kyle A., et al. "Flex ddG: Rosetta 
#                 ensemble-based estimation of changes in 
#                 protein–protein binding affinity upon mutation." 
#                 The Journal of Physical Chemistry B 122.21
#                 (2018): 5389-5399.


# version of the configuration file
version: 1


#--------------------- GENERAL PROTOCOL OPTIONS ----------------------#


# family the protocol belongs to
family: flexddg


#------------------------ PDB-RELATED OPTIONS ------------------------#


pdb:
  # whether PDB files containing multiple chains are allowed
  # (true for flexddg protocols since they are used to predict
  # the ΔΔG of binding)
  allow_multi_chains: True
  # whether PDB files with chain IDs missing are allowed
  # (false for flexddg protocols since chain IDs are needed to
  # discriminate between chains)
  allow_no_chain_ids: False


#--------------------- MUTATIONS-RELATED OPTIONS ---------------------#


# options regarding how mutations are defined in the mutations list
# file
mutations:
  # which kind of residue numbering is used in defining mutations
  # ("pdb" for flexddg protocols since the 'resfile' format used
  # by them requires residue numbering to be consistent with the
  # input PDB numbering)
  resnumbering: "pdb"
  # extra data associated with each mutation. For flexddg protocols,
  # the "_chaintomove_" attribute is defined to identify what chain(s)
  # will be moved away from the interface when computing the free
  # energy of the single chains.
  extra: !!seq ["_chaintomove_"]
  # number of structures to be generated for each mutation
  nstruct: 5
  # file mapping the names of the directories that will contain
  # data for the mutations to the mutations themselves as specified
  # in the mutations' list file
  mutinfofile: mutinfo.txt


#--------------------------- PROTOCOL STEPS --------------------------#


steps:
  
  # flexddg protocols consist in only one step
  flexddg:
    # name of the working directory where the step will be run
    wd: "flexddg"
    # whether (and how) to remove unnecessary files at the end
    # of the run
    cleanlevel: !!null
    # name of the flag file(s) that will be written and used
    # to run the step
    flagsfile: "flags.txt"
    # name of the Rosetta output file(s) that will be written
    output: "flexddg.out"
    # Rosetta options to be used in conjunction with the Rosetta
    # executable
    options:
      
      #------------------------ Input options ------------------------#
      
      # whether to ignore unrecognized residues found in the PDB
      -in:ignore_unrecognized_res: True
      # whether the PDB file will be read as a full-atom structure
      # as opposed to coarse-grained (should not be changed)
      -in:file:fullatom: True

      #------------------- Tracing/logging options -------------------#

      # logging level. 300 is INFO level.
      -out:level: 300
      # whether to add tracer channel name to the output
      -out:chname: True
      # whether to add a timestamp to tracer channel name
      -out:chtimestamp: True
      # save modelling times for each model in seconds
      -out:save_times: True

      #------------------------- Run options -------------------------#

      # whether to turn on/off checkpointing
      -run:checkpoint: True
      # whether to write out detailed version info, if it was 
      # available at compile time
      -run:version: True
      # whether to discard coordinates information for missing density
      # atoms (whose occupancy is zero) defined in the input structure
      -run:ignore_zero_occupancy: False

      #----------------------- Packing options -----------------------#

      # number of neighbors a residue must have before extra 
      # rotamers are used (Rosetta default is 18)
      -packing:extrachi_cutoff: 18
      # use extra chi1 sub-rotamers for all residues that pass the
      # extrachi_cutoff
      -packing:ex1: True
      # use extra chi2 sub-rotamers for all residues that pass the 
      # extrachi_cutoff
      -packing:ex2: True
      # file containing extra residue types to be included in the
      # packing palette
      -packing:packer_palette:extra_base_type_file: !!null

      #------------------- RosettaScripts options --------------------#

      # protocol XML file
      -parser:protocol: "Flex_ddG.xml"
      # variable substitutions for the XML parser, in the form
      # of name=value
      -parser:script_vars:
        # chain that will be moved away from the interface when 
        # computing the free energy of the single chains
        # It is defined in the mutations list file for each mutation
        # and substituted to the _chaintomove_ placeholder in the
        # flagfile written for each mutation.
        chaintomove: "_chaintomove_"
        # name of the resfile that will be written for each mutation
        resfile: "mutation.resfile"
        # output database files
        ddgdbfile: "ddg.db3"
        structdbfile: "struct.db3"
        # number of backrub trials
        backrubntrials: 35000
        # backrub trajectory stride
        backrubtrajstride: 7000
        # score function name
        scfname: "ref2015"

    # post-processing step to extract the PDB structures from the
    # database file they were written to (for flexddg protocols).
    extract_structures:
      # whether to extract the PDB structures from the database file
      extract: True
      # name of the flag file(s) that will be written and used
      # to run the step
      flagsfile: "flags_extract.txt"
      # name of the Rosetta output file(s) that will be written
      output: "extract_structures.out"
      # options to be passed to the Rosetta executable performing the
      # extraction (score_jd2)
      options:
        # whether the input file is a database file
        -in:use_database: True
        # whether the output files are PDB files
        -out:pdb: True

**Images of file structure and input files**
<img width="409" alt="Screenshot 2024-04-10 at 12 08 46" src="https://github.com/ELELAB/RosettaDDGPrediction/assets/166137229/a6adcb68-8e46-4fcd-9257-3fb141e67348">
[resfile.txt](https://github.com/ELELAB/RosettaDDGPrediction/files/14931331/resfile.txt)
[listfile.txt](https://github.com/ELELAB/RosettaDDGPrediction/files/14931332/listfile.txt)

**Comment by mtiberti** [comment]
hi @livmac101 , the last output you pasted seems the output of a partial run, it is just not complete yet. So looks like it was working correctly, for what I see here.

How did you determine that "the program gets stuck"? Have you checked what is happening in your system, if e.g. the processor is being used for these calculations? I would expect them to take quite a while (several hours), especially if you're not on a very powerful machine and using just four cores. Not all the files and directories are generated at the beginning of the calculation.

Nonetheless, I don't think we ever tested RosettaDDGPrediction on Mac, so any information is useful :)

**Comment by livmac101** [comment]
Hi @mtiberti Thank you very much for taking a look. That's helpful to know that now all of the files/folders are not generated right away and perhaps as you say I am simply not waiting long enough! I'll try it again today, with one model, amino acid change, position, etc. and report back.

**Comment by mtiberti** [comment]
@livmac101 just a reminder to let us know if this issue has been resolved, so we can close it. Thanks :)

**Comment by livmac101** [comment]
Hi @mtiberti, apologies for my later reply! I was able to run it in the end as suggested so the issue has been resolved. Thanks again for your help.

**Comment by mtiberti** [comment]
you're welcome! I'm closing this
